ressource:
    resource: "@RessourceBundle/Controller/"
    type:     annotation
    prefix:   /

rest:
    resource: "@RestBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /luckyPanel/documentation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"